version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    # Group updates by type to separate security from version updates
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
      npm-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
