/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test\\integration\\snapshots.js TAP snapshots are indentical on different platforms > report file contents matches snapshot 1`] = `
# Snapshot report for \`tests/test.js\`

The actual snapshot is saved in \`test.js.snap\`.

Generated by [AVA](https://ava.li).

## test title

> Snapshot 1

    {
      foo: 'bar',
    }

`

exports[`test\\integration\\snapshots.js TAP snapshots are indentical on different platforms > snap file contents matches snapshot 1`] = `
[65,86,65,32,83,110,97,112,115,104,111,116,32,118,49,10,1,0,96,125,132,194,94,90,129,191,178,119,214,222,241,186,124,16,31,139,8,0,0,0,0,0,0,3,83,96,96,96,96,100,56,249,160,245,87,84,110,212,139,51,170,130,47,39,165,232,77,96,100,0,129,48,32,102,98,96,7,179,25,217,25,153,12,129,180,57,16,139,48,178,11,49,178,249,39,101,165,38,151,48,50,194,153,130,130,130,76,255,235,25,24,121,24,24,25,25,24,249,128,202,152,68,25,153,25,24,89,132,24,153,211,242,243,225,236,164,196,34,0,142,104,247,114,118,0,0,0]
`
