blank_issues_enabled: true
contact_links:
  - name: Questions? Ideas? Something to share?
    url: https://github.com/avajs/ava/discussions
  - name: Babel
    url: https://github.com/avajs/babel/issues
    about: Report a bug with AVA's Babel integration
