'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const concordance = require('concordance');
const indentString = require('indent-string');
const convertSourceMap = require('convert-source-map');
const slash = require('slash');
const writeFileAtomic = require('write-file-atomic');
const mem = require('mem');

const concordanceOptions = require('./concordance-options').snapshotManager;

// Increment if encoding layout or Concordance serialization versions change. Previous AVA versions will not be able to
// decode buffers generated by a newer version, so changing this value will require a major version bump of AVA itself.
// The version is encoded as an unsigned 16 bit integer.
const VERSION = 3;

const VERSION_HEADER = Buffer.alloc(2);
VERSION_HEADER.writeUInt16LE(VERSION);

// The decoder matches on the trailing newline byte (0x0A).
const READABLE_PREFIX = Buffer.from(`AVA Snapshot v${VERSION}\n`, 'ascii');
const REPORT_SEPARATOR = Buffer.from('\n\n', 'ascii');
const REPORT_TRAILING_NEWLINE = Buffer.from('\n', 'ascii');

const MD5_HASH_LENGTH = 16;

class SnapshotError extends Error {
	constructor(message, snapPath) {
		super(message);
		this.name = 'SnapshotError';
		this.snapPath = snapPath;
	}
}
exports.SnapshotError = SnapshotError;

class ChecksumError extends SnapshotError {
	constructor(snapPath) {
		super('Checksum mismatch', snapPath);
		this.name = 'ChecksumError';
	}
}
exports.ChecksumError = ChecksumError;

class VersionMismatchError extends SnapshotError {
	constructor(snapPath, version) {
		super('Unexpected snapshot version', snapPath);
		this.name = 'VersionMismatchError';
		this.snapVersion = version;
		this.expectedVersion = VERSION;
	}
}
exports.VersionMismatchError = VersionMismatchError;

const LEGACY_SNAPSHOT_HEADER = Buffer.from('// Jest Snapshot v1');
function isLegacySnapshot(buffer) {
	return LEGACY_SNAPSHOT_HEADER.equals(buffer.slice(0, LEGACY_SNAPSHOT_HEADER.byteLength));
}

class LegacyError extends SnapshotError {
	constructor(snapPath) {
		super('Legacy snapshot file', snapPath);
		this.name = 'LegacyError';
	}
}
exports.LegacyError = LegacyError;

function tryRead(file) {
	try {
		return fs.readFileSync(file);
	} catch (error) {
		if (error.code === 'ENOENT') {
			return null;
		}

		throw error;
	}
}

function formatEntry(snapshot) {
	const {buffer} = snapshot;
	let {label} = snapshot;
	const descriptor = concordance.deserialize(buffer);

	if (label) {
		label = `> ${label}\n\n`;
	}

	const codeBlock = indentString(concordance.formatDescriptor(descriptor, concordanceOptions), 4);
	return Buffer.from(label + codeBlock, 'utf8');
}

function combineEntries(blocksByTitle, ordering) {
	const encoder = new Encoder();
	const sortedBlocks = sortBlocksByTitle(blocksByTitle, ordering);

	for (const [title, {snapshots}] of sortedBlocks) {
		const last = snapshots[snapshots.length - 1];
		encoder.writeFixedString(`\n\n## ${title}\n\n`);

		for (const snapshot of snapshots) {
			encoder.writeFixedBuffer(formatEntry(snapshot));

			if (snapshot !== last) {
				encoder.writeFixedBuffer(REPORT_SEPARATOR);
			}
		}
	}

	return encoder;
}

function generateReport(relFile, snapFile, blocksByTitle, ordering) {
	const encoder = new Encoder();
	const header = Buffer.from(`# Snapshot report for \`${slash(relFile)}\`

The actual snapshot is saved in \`${snapFile}\`.

Generated by [AVA](https://avajs.dev).`, 'utf8');
	encoder.writeFixedBuffer(header);

	const combined = combineEntries(blocksByTitle, ordering);
	encoder.append(combined);

	encoder.writeFixedBuffer(REPORT_TRAILING_NEWLINE);
	return encoder.toBuffer();
}

class Encoder {
	constructor() {
		this.buffers = [];
		this.byteOffset = 0;
	}

	writeUInt32LE(value) {
		const buffer = Buffer.alloc(4);
		buffer.writeUInt32LE(value, 0);
		this.writeFixedBuffer(buffer);
	}

	writeFixedBuffer(buffer) {
		this.buffers.push(buffer);
		this.byteOffset += buffer.byteLength;
	}

	writeLPBuffer(buffer) {
		this.writeUInt32LE(buffer.byteLength);
		this.writeFixedBuffer(buffer);
	}

	writeFixedString(string, encoding = 'utf8') {
		this.writeFixedBuffer(Buffer.from(string, encoding));
	}

	writeLPString(string, encoding = 'utf8') {
		const buffer = Buffer.from(string, encoding);
		this.writeLPBuffer(buffer);
	}

	toBuffer() {
		return Buffer.concat(this.buffers, this.byteOffset);
	}

	append({buffers, byteOffset}) {
		this.buffers.splice(this.buffers.length, 0, ...buffers);
		this.byteOffset += byteOffset;
	}
}

class Decoder {
	constructor(buffer, byteOffset = 0) {
		this.buffer = buffer;
		this.byteOffset = byteOffset;
	}

	readUInt32LE() {
		const value = this.buffer.readUInt32LE(this.byteOffset);
		this.byteOffset += 4;
		return value;
	}

	readFixedBuffer(byteLength) {
		const value = this.buffer.subarray(this.byteOffset, this.byteOffset + byteLength);
		this.byteOffset += byteLength;
		return value;
	}

	readLPBuffer() {
		const byteLength = this.readUInt32LE();
		return this.readFixedBuffer(byteLength);
	}

	readLPString(encoding = 'utf8') {
		const buffer = this.readLPBuffer();
		return buffer.toString(encoding);
	}
}

function sortBlocksByTitle(blocksByTitle, ordering) {
	const sorted = new Map();

	for (const title of ordering) {
		const block = blocksByTitle.get(title);

		if (block) {
			sorted.set(title, block);
		}
	}

	for (const title of [...blocksByTitle.keys()].filter(key => !sorted.has(key)).sort()) {
		sorted.set(title, blocksByTitle.get(title));
	}

	return sorted;
}

function encodeSnapshots(blocksByTitle, ordering) {
	blocksByTitle = sortBlocksByTitle(blocksByTitle, ordering);
	const encoder = new Encoder();

	encoder.writeUInt32LE(blocksByTitle.size);

	for (const [title, {snapshots}] of blocksByTitle.entries()) {
		encoder.writeLPString(title);
		encoder.writeUInt32LE(snapshots.length);

		for (const {label, buffer} of snapshots) {
			encoder.writeLPString(label);
			encoder.writeLPBuffer(buffer);
		}
	}

	const compressed = zlib.gzipSync(encoder.toBuffer());
	compressed[9] = 0x03; // Override the GZip header containing the OS to always be Linux
	const md5sum = crypto.createHash('md5').update(compressed).digest();
	return Buffer.concat([
		READABLE_PREFIX,
		VERSION_HEADER,
		md5sum,
		compressed
	], READABLE_PREFIX.byteLength + VERSION_HEADER.byteLength + MD5_HASH_LENGTH + compressed.byteLength);
}

function decodeSnapshots(buffer, snapPath) {
	if (isLegacySnapshot(buffer)) {
		throw new LegacyError(snapPath);
	}

	// The version starts after the readable prefix, which is ended by a newline
	// byte (0x0A).
	const versionOffset = buffer.indexOf(0x0A) + 1;
	const version = buffer.readUInt16LE(versionOffset);
	if (version !== VERSION) {
		throw new VersionMismatchError(snapPath, version);
	}

	const md5sumOffset = versionOffset + 2;
	const compressedOffset = md5sumOffset + MD5_HASH_LENGTH;
	const compressed = buffer.slice(compressedOffset);

	const md5sum = crypto.createHash('md5').update(compressed).digest();
	const expectedSum = buffer.slice(md5sumOffset, compressedOffset);
	if (!md5sum.equals(expectedSum)) {
		throw new ChecksumError(snapPath);
	}

	const decompressed = zlib.gunzipSync(compressed);
	const decoder = new Decoder(decompressed);
	const numberBlocks = decoder.readUInt32LE();
	const blocksByTitle = new Map();

	for (let blockIndex = 0; blockIndex < numberBlocks; blockIndex++) {
		const title = decoder.readLPString();
		const numberSnapshots = decoder.readUInt32LE();
		const snapshots = [];

		for (let snapshotIndex = 0; snapshotIndex < numberSnapshots; snapshotIndex++) {
			const label = decoder.readLPString();
			const buffer = decoder.readLPBuffer();

			snapshots.push({label, buffer});
		}

		blocksByTitle.set(title, {snapshots});
	}

	return blocksByTitle;
}

class Manager {
	constructor(options) {
		this.dir = options.dir;
		this.recordNewSnapshots = options.recordNewSnapshots;
		this.relFile = options.relFile;
		this.reportFile = options.reportFile;
		this.snapFile = options.snapFile;
		this.snapPath = options.snapPath;
		this.oldBlocksByTitle = options.oldBlocksByTitle;
		this.newBlocksByTitle = options.newBlocksByTitle;
		this.ordering = options.ordering || [...options.newBlocksByTitle.keys()];

		this.hasChanges = false;
	}

	compare(options) {
		const block = this.newBlocksByTitle.get(options.belongsTo);
		const snapshot = block && block.snapshots[options.index];
		const snapshotBuffer = snapshot && snapshot.buffer;

		if (!snapshotBuffer) {
			if (!this.recordNewSnapshots) {
				return {pass: false};
			}

			if (options.deferRecording) {
				const record = this.deferRecord(options);
				return {pass: true, record};
			}

			this.record(options);
			return {pass: true};
		}

		const actual = concordance.deserialize(snapshotBuffer, concordanceOptions);
		const expected = concordance.describe(options.expected, concordanceOptions);
		const pass = concordance.compareDescriptors(actual, expected);

		return {actual, expected, pass};
	}

	deferRecord(options, changed = true) {
		const descriptor = concordance.describe(options.expected, concordanceOptions);
		const snapshotBuffer = concordance.serialize(descriptor);
		const {belongsTo} = options;

		return () => { // Must be called in order!
			this.hasChanges = this.hasChanges || changed;

			let block = this.newBlocksByTitle.get(belongsTo);
			if (!block) {
				block = {snapshots: []};
				this.newBlocksByTitle.set(belongsTo, block);
			}

			const {snapshots} = block;

			if (options.index > snapshots.length) {
				throw new RangeError(`Cannot record snapshot ${options.index} for ${JSON.stringify(options.belongsTo)}, exceeds expected index of ${snapshots.length}`);
			}

			if (options.index < snapshots.length) {
				throw new RangeError(`Cannot record snapshot ${options.index} for ${JSON.stringify(options.belongsTo)}, already exists`);
			}

			snapshots.push({
				label: options.label,
				buffer: snapshotBuffer
			});
		};
	}

	record(options, changed = true) {
		const record = this.deferRecord(options, changed);
		record();
	}

	setOrdering(ordering) {
		this.ordering = ordering;
	}

	skipBlock(title) {
		const block = this.oldBlocksByTitle.get(title);

		if (block) {
			this.newBlocksByTitle.set(title, block);
		}
	}

	skipSnapshot({belongsTo, index}) {
		const oldBlock = this.oldBlocksByTitle.get(belongsTo);
		const snapshot = oldBlock && oldBlock.snapshots[index];

		if (snapshot) {
			// Retaining the label from the old snapshot, so as not to assume that the
			// snapshot.skip() arguments are well-formed
			const {buffer: expected, label} = snapshot;
			this.record({belongsTo, index, expected, label}, false);
		}
	}

	save() {
		if (!this.hasChanges) {
			return null;
		}

		const {snapPath} = this;
		const buffer = encodeSnapshots(this.newBlocksByTitle, this.ordering);

		const reportPath = path.join(this.dir, this.reportFile);
		const reportBuffer = generateReport(this.relFile, this.snapFile, this.newBlocksByTitle, this.ordering);

		fs.mkdirSync(this.dir, {recursive: true});

		const paths = [snapPath, reportPath];
		const tmpfileCreated = tmpfile => paths.push(tmpfile);
		writeFileAtomic.sync(snapPath, buffer, {tmpfileCreated});
		writeFileAtomic.sync(reportPath, reportBuffer, {tmpfileCreated});
		return paths;
	}
}

const resolveSourceFile = mem(file => {
	const testDir = path.dirname(file);
	const buffer = tryRead(file);
	if (!buffer) {
		return file; // Assume the file is stubbed in our test suite.
	}

	const source = buffer.toString();
	const converter = convertSourceMap.fromSource(source) || convertSourceMap.fromMapFileSource(source, testDir);
	if (converter) {
		const map = converter.toObject();
		const firstSource = `${map.sourceRoot || ''}${map.sources[0]}`;
		return path.resolve(testDir, firstSource);
	}

	return file;
});

const determineSnapshotDir = mem(({file, fixedLocation, projectDir}) => {
	const testDir = path.dirname(resolveSourceFile(file));
	if (fixedLocation) {
		const relativeTestLocation = path.relative(projectDir, testDir);
		return path.join(fixedLocation, relativeTestLocation);
	}

	const parts = new Set(path.relative(projectDir, testDir).split(path.sep));
	if (parts.has('__tests__')) {
		return path.join(testDir, '__snapshots__');
	}

	if (parts.has('test') || parts.has('tests')) { // Accept tests, even though it's not in the default test patterns
		return path.join(testDir, 'snapshots');
	}

	return testDir;
}, {cacheKey: ([{file}]) => file});

exports.determineSnapshotDir = determineSnapshotDir;

function determineSnapshotPaths({file, fixedLocation, projectDir}) {
	const dir = determineSnapshotDir({file, fixedLocation, projectDir});
	const relFile = path.relative(projectDir, resolveSourceFile(file));
	const name = path.basename(relFile);
	const reportFile = `${name}.md`;
	const snapFile = `${name}.snap`;

	return {
		dir,
		relFile,
		snapFile,
		reportFile
	};
}

function cleanFile(file) {
	try {
		fs.unlinkSync(file);
		return [file];
	} catch (error) {
		if (error.code === 'ENOENT') {
			return [];
		}

		throw error;
	}
}

// Remove snapshot and report if they exist. Returns an array containing the
// paths of the touched files.
function cleanSnapshots({file, fixedLocation, projectDir}) {
	const {dir, snapFile, reportFile} = determineSnapshotPaths({file, fixedLocation, projectDir});

	return [
		...cleanFile(path.join(dir, snapFile)),
		...cleanFile(path.join(dir, reportFile))
	];
}

exports.cleanSnapshots = cleanSnapshots;

function load({file, fixedLocation, projectDir, recordNewSnapshots, updating}) {
	const {dir, relFile, snapFile, reportFile} = determineSnapshotPaths({file, fixedLocation, projectDir});
	const snapPath = path.join(dir, snapFile);

	const buffer = tryRead(snapPath);
	const blocksByTitle = buffer ? decodeSnapshots(buffer, snapPath) : new Map();

	return new Manager({
		dir,
		recordNewSnapshots,
		relFile,
		reportFile,
		snapFile,
		snapPath,
		oldBlocksByTitle: blocksByTitle,
		newBlocksByTitle: updating ? new Map() : blocksByTitle
	});
}

exports.load = load;
